// ===========================================================================
//  modal-logic.js
//  The lattice of normal modal logics K .. S5 generated by the axioms
//  t, 4, d, b, 5 (over the base K), as a dynamically-computed Hasse diagram.
//
//  Each logic is identified with the set of FRAME PROPERTIES it forces:
//      s = serial      (axiom d : []A -> <>A)
//      r = reflexive   (axiom t : []A -> A)
//      y = symmetric   (axiom b :   A -> []<>A)
//      x = transitive  (axiom 4 : []A -> [][]A)
//      e = euclidean   (axiom 5 : <>A -> []<>A)
//
//  Adding an axiom = adding its property, then closing under the implications
//  between frame conditions.  Because of those implications the 2^5 = 32
//  axiom-subsets collapse to exactly 15 distinct logics.
// ===========================================================================

// axiom letter -> frame property it introduces
export const AX_PROP = { d: "s", t: "r", b: "y", "4": "x", "5": "e" };

// display order (matches the figure: t, 4, d, b, 5)
export const AXIOMS = ["t", "4", "d", "b", "5"];

// human-readable axiom schemata (□ = [], ◇ = <>)
export const AX_FORMULA = {
  k: "□(A→B) → (□A → □B)",
  t: "□A → A",
  "4": "□A → □□A",
  d: "□A → ◇A",
  b: "A → □◇A",
  "5": "◇A → □◇A",
};

export const AX_NAME = {
  t: "reflexive", "4": "transitive", d: "serial", b: "symmetric", "5": "euclidean",
};

// one colour per axiom; the +5 (euclidean) family is green, as requested.
export const AX_COLOR = {
  t: "#ef4444", // reflexivity  – red
  "4": "#3b82f6", // transitivity – blue
  d: "#f59e0b", // seriality    – amber
  b: "#a855f7", // symmetry     – violet
  "5": "#22c55e", // euclidean    – green
};

// When a cover edge could be labelled by more than one axiom (because of the
// collapses near S5), pick one in this priority order.  Putting 5 first keeps
// the euclidean family green (e.g. KB->KB5, S4->S5); t beats b/d for the
// "becomes reflexive -> S5" edges.
const LABEL_PRIORITY = ["5", "t", "4", "b", "d"];

// Close a set of frame properties under the standard implications.
function closure(props) {
  const s = new Set(props);
  let changed = true;
  while (changed) {
    changed = false;
    const add = (p) => { if (!s.has(p)) { s.add(p); changed = true; } };
    if (s.has("r")) add("s");                       // reflexive  => serial
    if (s.has("y") && s.has("x")) add("e");         // sym+trans  => euclidean
    if (s.has("y") && s.has("e")) add("x");         // sym+eucl   => transitive
    if (s.has("r") && s.has("e")) { add("y"); add("x"); } // refl+eucl => S5
    if (s.has("s") && s.has("y") && s.has("x")) add("r"); // ser+sym+trans => refl
  }
  return s;
}

// canonical key for a property set
const keyOf = (set) => [...set].sort().join("") || "_";

// property-key -> conventional logic name
export const NAMES = {
  "_": "K",
  "s": "D",
  "rs": "T",
  "x": "K4",
  "sx": "D4",
  "rsx": "S4",
  "y": "KB",
  "sy": "DB",
  "rsy": "TB",
  "e": "K5",
  "es": "D5",
  "ex": "K45",
  "esx": "D45",
  "exy": "KB5",
  "ersxy": "S5",
};

// Fixed 3-D coordinates for every logic (x = right, y = up, z = toward viewer).
//  - vertical axis y: not-serial (-3) -> serial (0) -> reflexive (+3)
//  - depth axis z:    +4 (transitivity) pushes a node toward the back
//  - x:               +b (symmetry) pushes right; +5 nudges right & back
export const COORDS = {
  K:   [0.0, -3, 3.0],
  D:   [0.0,  0, 3.0],
  T:   [0.0,  3, 3.0],
  KB:  [3.0, -3, 3.0],
  DB:  [3.0,  0, 3.0],
  TB:  [3.0,  3, 3.0],
  K4:  [0.0, -3, 0.0],
  D4:  [0.0,  0, 0.0],
  S4:  [0.0,  3, 0.0],
  K5:  [1.5, -3, 1.5],
  D5:  [1.5,  0, 1.5],
  K45: [1.5, -3, -1.5],
  D45: [1.5,  0, -1.5],
  KB5: [4.5, -3, -1.5],
  S5:  [4.5,  3, -1.5],
};

// ---------------------------------------------------------------------------
//  Public API
// ---------------------------------------------------------------------------

// All 15 logics (used to lay out / pre-create every node once).
export function allLogics() {
  return Object.entries(NAMES).map(([k, name]) => ({
    key: k,
    name,
    props: new Set(k === "_" ? [] : k.split("")),
    coord: COORDS[name],
  }));
}

const subseteq = (a, b) => [...a].every((p) => b.has(p));

// every subset of `arr`
function subsets(arr) {
  const out = [[]];
  for (const x of arr) {
    const len = out.length;
    for (let i = 0; i < len; i++) out.push([...out[i], x]);
  }
  return out;
}

// Given the set of currently-enabled axioms, compute the visible sub-lattice
// as a Hasse diagram: { nodes:[{key,name,props,coord}], edges:[{from,to,axiom,color}] }.
//
// A logic is visible iff it equals K + S for some subset S of the enabled
// axioms (so enabling only `t` shows T directly, since t derives d).
export function computeDiagram(enabled) {
  const en = AXIOMS.filter((a) => enabled.has(a));

  // 1. visible logics = closures of every subset of the enabled axioms
  const seen = new Map(); // key -> node
  for (const S of subsets(en)) {
    const props = closure(S.map((a) => AX_PROP[a]));
    const k = keyOf(props);
    if (!seen.has(k)) {
      const name = NAMES[k];
      seen.set(k, { key: k, name, props, coord: COORDS[name] });
    }
  }
  const nodes = [...seen.values()];

  // 2. cover relations within the visible set (A < B, nothing strictly between)
  const edges = [];
  for (const A of nodes) {
    for (const B of nodes) {
      if (A === B || !subseteq(A.props, B.props)) continue;
      const between = nodes.some(
        (C) => C !== A && C !== B &&
          subseteq(A.props, C.props) && subseteq(C.props, B.props)
      );
      if (between) continue;

      // which enabled axiom realises this cover (A + axiom == B)?
      const candidates = en.filter(
        (ax) => keyOf(closure([...A.props, AX_PROP[ax]])) === B.key
      );
      const axiom =
        LABEL_PRIORITY.find((a) => candidates.includes(a)) ||
        candidates[0] ||
        null;
      edges.push({
        from: A.name,
        to: B.name,
        axiom,
        color: axiom ? AX_COLOR[axiom] : "#9ca3af",
      });
    }
  }
  return { nodes, edges };
}
